export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";

export const FETCH_USER_PHOTOS = "FETCH_USER_PHOTOS";
export const FETCH_USER_PHOTOS_SUCCESS = "FETCH_USER_PHOTOS_SUCCESS";
export const FETCH_USER_PHOTOS_FAILURE = "FETCH_USER_PHOTOS_FAILURE";

export const FETCH_FIXED_USER = "FETCH_FIXED_USER";
export const FETCH_FIXED_USER_SUCCESS = "FETCH_FIXED_USER_SUCCESS";
export const FETCH_FIXED_USER_FAILURE = "FETCH_FIXED_USER_FAILURE";
