export const FETCH_RANDOM_PHOTOS = "FETCH_RANDOM_PHOTOS";
export const FETCH_RANDOM_PHOTOS_SUCCESS = "FETCH_RANDOM_PHOTOS_SUCCESS";
export const FETCH_RANDOM_PHOTOS_FAILURE = "FETCH_RANDOM_PHOTOS_FAILURE";
